--- #YAML:1.0
name:               WebService-Amazon-Route53-Caching
version:            0.3
abstract:           Caching layer on top of WebService::Amazon::Route53.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:                 ~
    WebService::Amazon::Route53:  ~
resources:
    license:  http://dev.perl.org/licenses/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
