--- #YAML:1.0
name:               WebService-Amazon-Route53-Caching
version:            0.4.1
abstract:           Caching layer on top of WebService::Amazon::Route53.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:                 0
    perl:                 5.008
    Redis:                0
    WebService::Amazon::Route53:  0
resources:
    bugtracker:  https://github.com/skx/WebService--Amazon--Route53--Caching/issues
    homepage:    https://github.com/skx/WebService--Amazon--Route53--Caching/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/WebService--Amazon--Route53--Caching.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
